services:
  eos_connect:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ohand/eos_connect:snapshot
    ports:
      - "8081:8081"
    volumes:
      - ./src/config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - eos_server

  eos_server:
    image: ghcr.io/akkudoktor/eos:latest
    ports:
      - "8503:8503"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
